### ISSUE TITLE
Possible typo in Transaction request model

### ISSUE THREAD

**Issue by kurbar** [solinor/paymenthighway-php-lib#3]
Transaction model has variable defined named `orderId`

```
public $orderId = null;
```

In constructor however `$orderId` is assigned to class variable `order`

```
public function __construct( $request, $amount, $currency, $blocking = true, $orderId = null )
...
$this->order = $orderId;
```

I'm assuming it should be `orderId` instead of `order` in constructor?

**Comment by jonni-larjomaa** [comment]
Yes it is a typo, should be orderId. This bug will be fixed and is available in next version.

**Comment by Kostersson** [comment]
Field name should be "order". Fixed in commit https://github.com/solinor/paymenthighway-php-lib/commit/abc26d842a9c3b85ccefaab69ff1b0689963f59f
